name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Or other desired OS

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: git submodule update --init --recursive && sudo apt-get update && sudo apt-get install -y build-essential cmake

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DBUILD_TESTS=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Run Tests
      run: ctest --test-dir ${{github.workspace}}/build --output-on-failure