name: C++ Build and Test

on:
  workflow_call:
    inputs:
      build-type:
        required: false
        default: 'Debug'
        type: string
      enable-tests:
        required: false
        default: true
        type: boolean
    secrets:
      github-token:
        required: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libomp-dev libopenmpi-dev libblas-dev

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build -DBUILD_TESTS=${{ inputs.enable-tests }}

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Run Tests
      if: ${{ inputs.enable-tests }}
      run: ctest --test-dir ${{github.workspace}}/build --output-on-failure
